## DialogueChoiceMenu — gamepad-navigable player dialogue choice overlay.
##
## Displays a RetroPanel-styled vertical list of dialogue choices generated by
## DialogueChoiceGenerator (or supplied directly).  Full controller, keyboard,
## and mouse support.
##
## Usage (await pattern — call from a coroutine):
##
##   var menu := DialogueChoiceMenu.new()
##   add_child(menu)
##   var chosen: String = await menu.present(["Tell me more.", "Farewell."])
##   menu.queue_free()
##
## If the player cancels (B / Escape / RClick), `choice_cancelled` is emitted
## and `present()` returns the CANCEL sentinel ("").
##
## Anchor notes:
##   - The panel anchors to the bottom-centre of the viewport, matching
##     the bottom-third positioning typical of JRPG dialogue boxes.
##   - The caller may reposition by setting `panel_offset` before calling
##     `present()`.
##
## Signals:
##   choice_made(text: String)  — player confirmed a choice
##   choice_cancelled()         — player pressed cancel without selecting

extends Control
class_name DialogueChoiceMenu


# ── Signals ───────────────────────────────────────────────────────────────────

## Emitted when the player confirms a choice.  `text` is the raw choice string.
signal choice_made(text: String)

## Emitted when the player presses cancel without confirming a choice.
signal choice_cancelled()


# ── Layout constants ──────────────────────────────────────────────────────────

const PANEL_W:        int   = 480
const ROW_H:          int   = 40
const HEADER_H:       int   = 0    # No header row in this menu variant
const PADDING_TOP:    int   = 12
const PADDING_SIDE:   int   = 16
const PADDING_BOTTOM: int   = 12
const ROW_FONT_SIZE:  int   = 18
const HINT_FONT_SIZE: int   = 13

## Vertical offset from the bottom of the viewport (negative = up).
## Callers may override before calling present().
var panel_offset: Vector2 = Vector2(0.0, -20.0)


# ── Palette (RetroPanel blue family) ─────────────────────────────────────────

const COL_BG:           Color = Color(0.06, 0.08, 0.14, 0.96)
const COL_BORDER:       Color = Color(0.7,  0.85, 1.0,  1.0 )
const COL_BORDER_SHADE: Color = Color(0.15, 0.20, 0.40, 1.0 )
const COL_ROW_NORMAL:   Color = Color(0.85, 0.90, 1.0,  1.0 )
const COL_ROW_SELECTED: Color = Color(1.0,  0.95, 0.6,  1.0 )
const COL_HINT:         Color = Color(0.6,  0.70, 0.85, 1.0 )
const COL_CURSOR:       Color = Color(1.0,  0.95, 0.6,  1.0 )
const COL_DIM:          Color = Color(0.0,  0.0,  0.0,  0.55)


# ── CANCEL sentinel ───────────────────────────────────────────────────────────

## Return value of present() when the player cancels.
const CHOICE_CANCELLED: String = ""


# ── State ─────────────────────────────────────────────────────────────────────

var _choices:     Array[String] = []
var _selection:   int           = 0
var _panel:       Control       = null
var _row_nodes:   Array         = []   # Label nodes, one per choice
var _hint_label:  Label         = null
var _active:      bool          = false
var _result:      String        = CHOICE_CANCELLED


# ── Public API ────────────────────────────────────────────────────────────────

## Present `choices` to the player and wait for a selection or cancellation.
##
## Returns the chosen String, or CHOICE_CANCELLED ("") if the player cancelled.
## MUST be awaited.
func present(choices: Array) -> String:
	if _active or choices.is_empty():
		return CHOICE_CANCELLED

	_active = true
	_result = CHOICE_CANCELLED
	_selection = 0
	_choices.clear()

	# Coerce to Array[String], silently dropping non-String entries.
	for item in choices:
		if item is String and not (item as String).strip_edges().is_empty():
			_choices.append(item as String)

	if _choices.is_empty():
		_active = false
		return CHOICE_CANCELLED

	_build_ui()
	_highlight()

	# Wait for the player to make a choice or cancel.
	await _wait_for_resolution()

	_active = false
	return _result


## Dismiss the menu programmatically (e.g. on scene change).
## Equivalent to the player pressing cancel.
func dismiss() -> void:
	if not _active:
		return
	_result = CHOICE_CANCELLED
	_resolve()


# ── UI construction ───────────────────────────────────────────────────────────

func _ready() -> void:
	# Transparent full-screen layer to capture input.
	anchor_left   = 0.0
	anchor_top    = 0.0
	anchor_right  = 1.0
	anchor_bottom = 1.0
	offset_left   = 0
	offset_top    = 0
	offset_right  = 0
	offset_bottom = 0
	mouse_filter  = Control.MOUSE_FILTER_STOP


func _build_ui() -> void:
	# Remove any pre-existing panel from a previous present() call.
	if _panel != null and is_instance_valid(_panel):
		_panel.queue_free()
		_panel = null
	_row_nodes.clear()

	# Dim backdrop.
	var dim := ColorRect.new()
	dim.color = COL_DIM
	dim.anchor_right  = 1.0
	dim.anchor_bottom = 1.0
	dim.mouse_filter  = Control.MOUSE_FILTER_IGNORE
	add_child(dim)

	# Calculate panel height from number of choices.
	var panel_h: int = PADDING_TOP + _choices.size() * ROW_H + PADDING_BOTTOM + 28  # +28 for hint row

	_panel = RetroPanel.create_panel(
		PANEL_W,
		panel_h,
		COL_BG,
		COL_BORDER,
		COL_BORDER_SHADE,
	)

	# Bottom-centre anchor.
	var vp_size: Vector2 = get_viewport_rect().size
	_panel.position = Vector2(
		(vp_size.x - PANEL_W) / 2.0 + panel_offset.x,
		vp_size.y - panel_h + panel_offset.y,
	)
	_panel.mouse_filter = Control.MOUSE_FILTER_IGNORE
	add_child(_panel)

	# Choice rows.
	for i in _choices.size():
		var row := Label.new()
		row.text = "  " + _choices[i]
		row.add_theme_font_size_override("font_size", ROW_FONT_SIZE)
		row.add_theme_color_override("font_color", COL_ROW_NORMAL)
		row.position  = Vector2(PADDING_SIDE, PADDING_TOP + i * ROW_H)
		row.size      = Vector2(PANEL_W - PADDING_SIDE * 2, ROW_H)
		row.clip_text = false
		row.text_overrun_behavior = TextServer.OVERRUN_NO_TRIMMING
		row.mouse_filter = Control.MOUSE_FILTER_STOP
		_panel.add_child(row)
		_row_nodes.append(row)

		# Transparent button overlay for mouse hover + click.
		var btn := Button.new()
		btn.flat = true
		btn.set_anchors_preset(Control.PRESET_FULL_RECT)
		btn.mouse_filter = Control.MOUSE_FILTER_STOP
		var idx_now: int = i  # Capture current index in closure.
		btn.mouse_entered.connect(_on_row_hover.bind(idx_now))
		btn.pressed.connect(_on_row_click.bind(idx_now))
		row.add_child(btn)

	# Divider above hint.
	var div := ColorRect.new()
	div.color    = Color(0.3, 0.4, 0.6, 0.7)
	div.position = Vector2(PADDING_SIDE, PADDING_TOP + _choices.size() * ROW_H + 4)
	div.size     = Vector2(PANEL_W - PADDING_SIDE * 2, 2)
	_panel.add_child(div)

	# Hint row.
	_hint_label = Label.new()
	_hint_label.text = "[A/Enter/Click] Confirm    [B/Esc/RClick] Cancel    (↑↓/D-pad)"
	_hint_label.position = Vector2(PADDING_SIDE, PADDING_TOP + _choices.size() * ROW_H + 8)
	_hint_label.size     = Vector2(PANEL_W - PADDING_SIDE * 2, 24)
	_hint_label.add_theme_font_size_override("font_size", HINT_FONT_SIZE)
	_hint_label.add_theme_color_override("font_color", COL_HINT)
	_hint_label.horizontal_alignment = HORIZONTAL_ALIGNMENT_CENTER
	_hint_label.clip_text = false
	_hint_label.text_overrun_behavior = TextServer.OVERRUN_NO_TRIMMING
	_panel.add_child(_hint_label)


# ── Input handling ────────────────────────────────────────────────────────────

func _input(event: InputEvent) -> void:
	if not _active:
		return

	# Right-click = cancel.
	if event is InputEventMouseButton:
		var mb := event as InputEventMouseButton
		if mb.pressed and mb.button_index == MOUSE_BUTTON_RIGHT:
			_cancel()
			get_viewport().set_input_as_handled()
			return
		# Mouse wheel = navigate.
		if mb.pressed and mb.button_index == MOUSE_BUTTON_WHEEL_UP:
			_move_selection(-1)
			get_viewport().set_input_as_handled()
			return
		if mb.pressed and mb.button_index == MOUSE_BUTTON_WHEEL_DOWN:
			_move_selection(1)
			get_viewport().set_input_as_handled()
			return

	if event.is_action_pressed("ui_up"):
		_move_selection(-1)
		get_viewport().set_input_as_handled()
	elif event.is_action_pressed("ui_down"):
		_move_selection(1)
		get_viewport().set_input_as_handled()
	elif event.is_action_pressed("ui_accept"):
		_confirm()
		get_viewport().set_input_as_handled()
	elif event.is_action_pressed("ui_cancel"):
		_cancel()
		get_viewport().set_input_as_handled()


# ── Selection logic ───────────────────────────────────────────────────────────

func _move_selection(delta: int) -> void:
	if _choices.is_empty():
		return
	_selection = (_selection + delta + _choices.size()) % _choices.size()
	_highlight()
	# Engine.has_singleton("SoundManager") is ALWAYS FALSE for autoloads in
	# Godot 4 — fetch the autoload from the scene tree root instead.
	var sm: Node = get_node_or_null("/root/SoundManager")
	if sm != null and sm.has_method("play_ui"):
		sm.play_ui("menu_move")


func _highlight() -> void:
	for i in _row_nodes.size():
		var row: Label = _row_nodes[i]
		if not is_instance_valid(row):
			continue
		if i == _selection:
			row.add_theme_color_override("font_color", COL_ROW_SELECTED)
			row.text = "▸ " + _choices[i]
		else:
			row.add_theme_color_override("font_color", COL_ROW_NORMAL)
			row.text = "  " + _choices[i]


func _confirm() -> void:
	if _selection < 0 or _selection >= _choices.size():
		return
	_result = _choices[_selection]
	# Bug #4: SoundManager bank has only menu_move/menu_select/menu_cancel,
	# so "menu_confirm" was silently a no-op (or a missing-key warning).
	# Use "menu_select" — the canonical confirm sound throughout the project.
	var sm: Node = get_node_or_null("/root/SoundManager")
	if sm != null and sm.has_method("play_ui"):
		sm.play_ui("menu_select")
	choice_made.emit(_result)
	_resolve()


func _cancel() -> void:
	_result = CHOICE_CANCELLED
	var sm: Node = get_node_or_null("/root/SoundManager")
	if sm != null and sm.has_method("play_ui"):
		sm.play_ui("menu_cancel")
	choice_cancelled.emit()
	_resolve()


# ── Mouse callbacks ───────────────────────────────────────────────────────────

func _on_row_hover(idx: int) -> void:
	if idx < 0 or idx >= _row_nodes.size():
		return
	if idx == _selection:
		return
	_selection = idx
	_highlight()
	var sm: Node = get_node_or_null("/root/SoundManager")
	if sm != null and sm.has_method("play_ui"):
		sm.play_ui("menu_move")


func _on_row_click(idx: int) -> void:
	if idx < 0 or idx >= _choices.size():
		return
	_selection = idx
	_highlight()
	_confirm()


# ── Async resolution helper ───────────────────────────────────────────────────

## Resolved flag used by _wait_for_resolution.
var _resolved: bool = false


func _resolve() -> void:
	_resolved = true
	# Tear down the UI after a short delay so the final highlight is visible.
	call_deferred("_teardown_ui")


func _teardown_ui() -> void:
	if _panel != null and is_instance_valid(_panel):
		_panel.queue_free()
		_panel = null
	_row_nodes.clear()
	_hint_label = null
	# Remove the dim backdrop (first ColorRect child).
	for child in get_children():
		if child is ColorRect:
			child.queue_free()


## Poll until _resolved is set; never blocks the main thread.
func _wait_for_resolution() -> void:
	_resolved = false
	while not _resolved:
		await get_tree().process_frame
