## NullBackend — zero-latency deterministic fallback backend.
##
## Always emits request_finished with ok=false on the next frame, routing every
## caller through its fallback path.  Used when:
##   - The LLM is disabled in settings.
##   - No other backend is ready.
##   - Unit tests want predictable fallback coverage.
##
## Primable with scripted responses: call prime(id, text) before submit() to
## make the next request with that id succeed with the given text.  This is
## the primary test-stubbing mechanism — tests prime expected responses and
## verify that the guard + fallback chain handles them correctly.
##
## Threading invariant: always on the main thread; uses call_deferred to ensure
## request_finished is never emitted synchronously inside submit() — callers
## using `await` on the signal must not receive it before their await is set up.

class_name NullBackend
extends LLMBackend

# ── Primed responses for testing ──────────────────────────────────────────────
# Maps id → text; consumed (deleted) once emitted.
var _primed: Dictionary = {}

# Tracks ids submitted but not yet resolved (so cancel_all works correctly).
var _pending: Array[String] = []


# ── LLMBackend overrides ──────────────────────────────────────────────────────

func backend_id() -> String:
	return "null"


## NullBackend is always ready — it is the last-resort fallback.
func is_ready() -> bool:
	return true


func supports_json() -> bool:
	return false


func supports_grammar() -> bool:
	return false


## Submit a request.  If the id has a primed response, that text is returned
## with ok=true; otherwise ok=false is returned with an empty text.
## Emission is deferred one frame so `await signal` patterns work correctly.
func submit(id: String, prompt: String, opts: Dictionary = {}) -> void:
	_pending.append(id)
	if _primed.has(id):
		var text: String = str(_primed[id])
		_primed.erase(id)
		call_deferred("_emit_success", id, text)
	else:
		call_deferred("_emit_failure", id, "NullBackend: no real model available")


func cancel(id: String) -> void:
	var idx: int = _pending.find(id)
	if idx >= 0:
		_pending.remove_at(idx)
		# Emit cancelled synchronously — the deferred _emit_* may still fire,
		# but LLMService ignores duplicate completions for finished ids.
		request_finished.emit(id, false, "", "cancelled")


func cancel_all() -> void:
	for id in _pending.duplicate():
		cancel(id)


# ── Test-stubbing API ─────────────────────────────────────────────────────────

## Prime a scripted response for the given request id.
## Call this before submit() in unit tests to control what the backend returns.
func prime(id: String, text: String) -> void:
	_primed[id] = text


## Prime a scripted response that will be returned for ANY request whose id
## starts with `prefix`.  Useful when the exact id is generated by LLMService.
## Note: exact-id primes take priority over prefix primes.
func prime_prefix(prefix: String, text: String) -> void:
	_primed["__prefix__" + prefix] = text


## Clear all primed responses.
func clear_primed() -> void:
	_primed.clear()


# ── Internal deferred emitters ────────────────────────────────────────────────

func _emit_success(id: String, text: String) -> void:
	_pending.erase(id)
	request_finished.emit(id, true, text, "")


func _emit_failure(id: String, error: String) -> void:
	_pending.erase(id)
	request_finished.emit(id, false, "", error)
