#!/usr/bin/env python3
"""VillageBar dancer 4-frame animation — retires the procedural
`_draw_dancer` (24x32 pixel-by-pixel composite) called by
VillageBar._generate_dancer_sprites (src/exploration/VillageBar.gd:261).

cowir-main msg 2779: "fix the DANCERS in the bar in the first village
so they're actually generated by a real sprite or using gpt-image."

Pipeline (one gpt-image-1 call at high):
  1. Generate a 2x2 contact sheet with 4 dance poses of the SAME dancer
  2. Split the 1024x1024 output into four 512x512 tiles
  3. Downscale each tile 512 -> 32 via LANCZOS -> BOX
  4. Chromakey pure white -> transparent
  5. Save as 4 separate PNGs under assets/sprites/npcs/dancer/frame_<n>.png

The 32x32 frame is a slight upsize from the current 24x32 procedural
(procedural is chibi with head at cx=12, ~8px tall head, ~30px total).
VillageBar renders via Sprite2D at position (20, -8) on the 3x2-tile
bar; 32x32 is close enough to the original silhouette that no engine
tweak is needed.

Cost: 1 x $0.167 (high) = ~$0.17
"""
import argparse, base64, io, os, sys, time
from pathlib import Path
from openai import OpenAI
from PIL import Image

PROJECT = Path(__file__).resolve().parent.parent
GAME_REPO = Path(os.environ.get(
    "GAME_REPO",
    "/home/struktured/projects/cowardly-irregular-artist-ship"
))
OUT_DIR = GAME_REPO / "assets" / "sprites" / "npcs" / "dancer"
RAW_DIR = PROJECT / "tmp" / "bar_dancer_regen"
RAW_DIR.mkdir(parents=True, exist_ok=True)
COST = {"low": 0.011, "medium": 0.042, "high": 0.167}

STYLE_PROMPT = (
    "16-bit JRPG pixel-art contact sheet, 2x2 grid layout showing 4 "
    "dance-pose frames of the SAME entertainer, identical character "
    "identity across all 4 tiles — same silhouette, same palette, "
    "same size, same lineart weight. Fully transparent background "
    "between tiles, no scenery, no shadows, no floor. Each tile "
    "centered in its quadrant. Character: a graceful young tavern "
    "DANCER, warm auburn-blonde shoulder-length hair styled into a "
    "loose ponytail bouncing with the motion, fair skin, cheerful "
    "smiling face with expressive dark eyes, wearing a fitted crimson-"
    "red flamenco-style tavern dress with a flowing ruffled skirt and "
    "a gold sash at the waist, matching red slippers, small brass "
    "hoop earrings visible. Body proportions: slightly-chibi, head "
    "1/3 of the body, legs 1/3, dress 1/3 — playful FF5-Sylph/Cara "
    "style. Poses (all four with the dancer smiling, mid-motion, arms "
    "raised gracefully, weight shifted onto one leg):\n"
    "Top-left: arms lifted high overhead in a V shape, weight on LEFT "
    "leg, right leg lifted with pointed toe, skirt flaring RIGHT.\n"
    "Top-right: arms extended wide to the sides (like a T), weight "
    "shifting through center, skirt swirled forward.\n"
    "Bottom-left: right arm raised high, left arm curved down and out "
    "at hip level, weight on RIGHT leg, left leg lifted with pointed "
    "toe, skirt flaring LEFT.\n"
    "Bottom-right: arms crossed elegantly in front of the chest (as if "
    "mid-clap), weight centered, both feet on the ground, skirt "
    "settled. Same character every pose — bright cheerful entertainer, "
    "clean pixel-art lineart, bold outlines, soft cel shading, no "
    "anti-aliasing artifacts, no floating pixels, no duplicate limbs, "
    "no scenery."
)


def downscale(tile_512: Image.Image, target: int = 32) -> Image.Image:
    img = tile_512.convert("RGBA")
    img = img.resize((target * 4, target * 4), Image.LANCZOS)
    return img.resize((target, target), Image.BOX)


def transparent_bg(img: Image.Image, threshold: int = 240) -> Image.Image:
    img = img.convert("RGBA")
    px = img.load(); W, H = img.size
    for y in range(H):
        for x in range(W):
            r, g, b, a = px[x, y]
            if r >= threshold and g >= threshold and b >= threshold:
                px[x, y] = (r, g, b, 0)
    return img


def call_gpt(client, prompt, quality, max_retries=3):
    for attempt in range(max_retries):
        try:
            resp = client.images.generate(model="gpt-image-1",
                                           prompt=prompt, size="1024x1024",
                                           quality=quality, n=1)
            return Image.open(io.BytesIO(base64.b64decode(resp.data[0].b64_json)))
        except Exception as e:
            msg = str(e).lower()
            if "rate" in msg or "429" in msg:
                time.sleep(30 * (attempt + 1))
            elif any(k in msg for k in ("billing", "quota", "insufficient")):
                raise
            else:
                print(f"  Error: {e}; retry"); time.sleep(5)
    raise RuntimeError("failed after retries")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--quality", choices=["low", "medium", "high"], default="high")
    ap.add_argument("--frame-size", type=int, default=32,
                    help="output PNG frame size (default 32)")
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    if args.dry_run:
        print(f"DRY RUN — bar dancer 4-frame sheet at {args.quality} "
              f"(~${COST[args.quality]:.3f})")
        print(f"  output: {OUT_DIR}/frame_<0..3>.png @ {args.frame_size}x{args.frame_size}")
        return 0

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    client = OpenAI(); unit = COST[args.quality]
    print(f"[bar_dancer] gpt-image-1 ({args.quality}, ${unit:.3f})")
    sheet_1024 = call_gpt(client, STYLE_PROMPT, args.quality)
    raw_path = RAW_DIR / f"bar_dancer_raw_{args.quality}.png"
    sheet_1024.save(raw_path)
    print(f"  raw: {raw_path.relative_to(PROJECT)}")

    # Split 1024x1024 into 4 x 512x512 tiles (row-major: TL, TR, BL, BR)
    half = 512
    tiles = [
        sheet_1024.crop((0, 0, half, half)),
        sheet_1024.crop((half, 0, 1024, half)),
        sheet_1024.crop((0, half, half, 1024)),
        sheet_1024.crop((half, half, 1024, 1024)),
    ]
    for i, tile in enumerate(tiles):
        frame = transparent_bg(downscale(tile, args.frame_size))
        out = OUT_DIR / f"frame_{i}.png"
        frame.save(out)
        print(f"  frame {i} → {out.relative_to(GAME_REPO)}")
    print(f"\nTotal spent: ${unit:.3f}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
