extends GutTest

## tick 343: AutogrindSystem.on_battle_victory's item-tracking loop
## skips the "gold" key.
##
## Pre-fix tick 342 added items_gained["gold"] as the channel for
## passing autogrind gold from GameLoop to AutogrindSystem. But the
## item-tracking loop at line ~499 treated "gold" like any other item
## ID and pushed the gold amount into total_items_gained:
##
##   for item_id in items_gained:
##       total_items_gained[item_id] += quantity
##
## AutogrindController.get_grind_stats counts total_items_gained
## values as item drops (line ~568). So after a single autogrind
## battle that produced 50 gold, the "items obtained" counter would
## report 50 items. After a 30-min session: thousands of "gold" items.
##
## Fix: filter out the "gold" key from the item-tracking loop. The
## party_gold credit path below handles gold separately.

const AUTOGRIND_SYSTEM_PATH := "res://src/autogrind/AutogrindSystem.gd"


func _read(p: String) -> String:
	return FileAccess.get_file_as_string(p)


# ── Source pin: gold filter in the loop ─────────────────────────────

func before_each() -> void:
	AutogrindSystem._test_disable_persistence = true


func test_gold_filter_in_loop() -> void:
	var src := _read(AUTOGRIND_SYSTEM_PATH)
	var fn_idx: int = src.find("func on_battle_victory")
	assert_gt(fn_idx, -1)
	var next_fn: int = src.find("\nfunc ", fn_idx + 1)
	var body: String = src.substr(fn_idx, next_fn - fn_idx) if next_fn > 0 else src.substr(fn_idx)
	# Find the for-loop block.
	var loop_idx: int = body.find("for item_id in items_gained:")
	assert_gt(loop_idx, -1)
	var loop_body: String = body.substr(loop_idx, 400)
	assert_true(loop_body.contains("if item_id == \"gold\":"),
		"item-tracking loop must explicitly skip 'gold' — tick 342's gold channel uses items_gained but it's not a real item")
	assert_true(loop_body.contains("continue"),
		"the gold guard must be a continue (skip), not a noop")


# ── Behavioral: gold doesn't inflate total_items_gained ─────────────

func test_gold_does_not_inflate_items_gained() -> void:
	assert_not_null(AutogrindSystem, "AutogrindSystem autoload required")
	if AutogrindSystem == null:
		return

	# Snapshot.
	var prior_items: Dictionary = AutogrindSystem.total_items_gained.duplicate()
	var prior_gold: int = GameState.party_gold if GameState else 0
	AutogrindSystem.total_items_gained = {}
	AutogrindSystem.grind_party = []
	AutogrindSystem.current_region_id = ""
	AutogrindSystem._grind_stats["total_gold"] = 0
	if GameState:
		GameState.party_gold = 0

	# Drive: pass items_gained with gold AND a real item.
	AutogrindSystem.on_battle_victory(0, {"gold": 500, "potion": 2})

	# total_items_gained must contain "potion" but NOT "gold".
	assert_eq(int(AutogrindSystem.total_items_gained.get("potion", 0)), 2,
		"real items (potion) must still be tracked")
	assert_false(AutogrindSystem.total_items_gained.has("gold"),
		"'gold' key must NOT be in total_items_gained — would inflate the items counter")

	# Cleanup.
	AutogrindSystem.total_items_gained = prior_items
	AutogrindSystem._grind_stats["total_gold"] = 0
	if GameState:
		GameState.party_gold = prior_gold


# ── Behavioral: gold still credits party_gold (tick 342 still works) ─

func test_gold_still_credits_party_gold_after_filter() -> void:
	# Regression guard: the filter must skip the items loop but NOT
	# skip the party_gold update below.
	assert_not_null(GameState, "GameState autoload required")
	assert_not_null(AutogrindSystem, "AutogrindSystem autoload required")
	if GameState == null or AutogrindSystem == null:
		return

	var prior_gold: int = GameState.party_gold
	GameState.party_gold = 0
	AutogrindSystem.grind_party = []
	AutogrindSystem.current_region_id = ""
	AutogrindSystem._grind_stats["total_gold"] = 0

	AutogrindSystem.on_battle_victory(0, {"gold": 100})

	assert_eq(GameState.party_gold, 100,
		"party_gold must still receive the gold (tick 342 fix must not regress)")

	GameState.party_gold = prior_gold
	AutogrindSystem._grind_stats["total_gold"] = 0


## FLOOR. A renamed member on the AutogrindSystem autoload does not fail — it ABORTS the arm at
## runtime, and GUT scores that Passing when the abort lands after the last assert (rung 3),
## which `.366`'s exit 4 cannot reach. `get()` / `has_method()` ANSWER rather than raise.
## ⚠️ Generated by scanning this file, and the first generation produced a key `"gd"` — the
## pattern matched `AutogrindSystem.gd` inside a res:// PATH LITERAL. Lines carrying a path are
## excluded now; a regex reading source cannot tell a member reach from a filename by shape.
## ⚠️ THIS LIST IS A SNAPSHOT, NOT A DERIVATION, and that is the live limit. It was derived once by
## a script from this file's own `_res.` / AutogrindSystem reaches and then written as literals — so
## a member reached by a NEW arm added later is not covered, and the list goes quietly incomplete
## rather than loudly wrong. @cowir-cutscenes' rule puts it on the wrong side of the line: a figure
## the guard's claim DEPENDS on should be derived, and this is one.
## Deliberately not converted to a runtime derivation, per @cowir-sfx's reasoning: doing that needs
## @cowir-ai's bare-Object exclusion, because a runtime scan of this file would collect the `get` and
## `has_method` calls THIS ARM ITSELF makes and pin the mechanism it is written in. That is a real
## defence against a real hazard, and writing it tonight would be shipping it untested. Correct as of
## 2026-09-16; if you add an arm that reaches a new member, add it here or derive the set properly.
const _FLOOR_ARM_NAME := "test_every_autogrind_member_this_file_reaches_still_exists"
const _PINNED_COUNT := 5

func test_every_autogrind_member_this_file_reaches_still_exists() -> void:
	## @cowir-ai's counter to the snapshot limit above, and it converts the failure mode rather than
	## documenting it: a static list fails toward INCOMPLETENESS — add a reach tomorrow and the floor
	## silently covers all-but-one. This counts the distinct members reached in the text BEFORE this
	## function, so the arm cannot count its own `get`/`has_method` calls — @cowir-ai's bare-Object
	## exclusion replaced by SCOPING, which they named as the alternative. A new reach reds here.
	var own_src: String = FileAccess.get_file_as_string(get_script().resource_path)
	var cut: int = own_src.find("func %s(" % _FLOOR_ARM_NAME)
	assert_gt(cut, 0, "CONTROL: located this arm, so the scoped slice is real")
	var before: String = own_src.substr(0, cut)
	var reached: Dictionary = {}
	## ⛔ SKIP PATH LITERALS. `AutogrindSystem.gd` inside a res:// string matched as a member named
	## "gd" — the same false positive fixed in the generator and reintroduced here.
	for raw_line in before.split("\n"):
		if raw_line.contains("res://") or raw_line.strip_edges().begins_with("#"):
			continue
		for m in RegEx.create_from_string("(?:_res|AutogrindSystem)\\.([A-Za-z_][A-Za-z_0-9]*)").search_all(raw_line):
			reached[m.get_string(1)] = true
	reached.erase("_test_disable_persistence")
	reached.erase("PER_BATTLE_METAS")   ## read from SOURCE on purpose — see the arm above
	gut.p("    reaches before this arm: %d | pinned: %d" % [reached.size(), _PINNED_COUNT])
	assert_gt(reached.size(), 0, "CONTROL: the scan found reaches, or this count proves nothing")
	assert_eq(reached.size(), _PINNED_COUNT,
		"this file now reaches %d distinct members and the floor pins %d — add the new one, the list is a snapshot: %s" % [reached.size(), _PINNED_COUNT, str(reached.keys())])

	var missing: Array = []
	if AutogrindSystem.get("_grind_stats") == null: missing.append("_grind_stats")
	if AutogrindSystem.get("current_region_id") == null: missing.append("current_region_id")
	if AutogrindSystem.get("grind_party") == null: missing.append("grind_party")
	if AutogrindSystem.get("total_items_gained") == null: missing.append("total_items_gained")
	if not AutogrindSystem.has_method("on_battle_victory"): missing.append("on_battle_victory()")
	assert_eq(missing, [],
		"AutogrindSystem no longer has these, so the arms above would ABORT into a silent pass: %s" % str(missing))
